#! /bin/bash

if [ "$1" = "match"]; then
matchcma $1 $2 -M
cat Match_${1}|grep '^>' > $2.ID
perl ~/rhil_project/scripts/parse_cma.pl $1 unsel $2.ID > $2.not.cma
cat $2.not.cma|grep '^>'|cut -f2 -d'>' > $2.not.cma.ID
perl ~/rhil_project/scripts/match.pl $2.not.cma.ID $3 > $2.not.cma.partition


mv Match_$1 $2.yes.cma
rm ${1}_exel.rtf $1.pdb $1.ras *.ID
